const course = [
  {
    id: 1,
    img: "/Coding.jpg",
    title: "Python for Data Science",
    instructor: "Prof. Gideon",
    price: 50,
    level: "Beginner",
    category: "Data",
    duration: "12 Hours",
    description: "Learn how to use Python for data analysis. This course covers libraries like Pandas, NumPy, and Matplotlib to help you visualize and interpret complex data.",
    willLearn: ["Python Syntax", "Data Cleaning", "Data Visualization", "Statistical Analysis"]
  },
  {
    id: 2,
    img: "/Coding.jpg",
    title: "Full-stack Web Development",
    instructor: "Gabriel N.",
    price: 89,
    level: "Intermediate",
    category: "Web",
    duration: "40 Hours",
    description: "Master both frontend and backend development. You will build real-world projects using React, Node.js, Express, and MongoDB.",
    willLearn: ["React.js Hooks", "Node.js Backend", "MongoDB Database", "REST APIs"]
  },
  {
    id: 3,
    img: "/UIUx.jpg",
    title: "UX Design Fundamentals",
    instructor: "Myles Daniel",
    price: 35,
    level: "Beginner",
    category: "Design",
    duration: "15 Hours",
    description: "Dive into the world of User Experience. Learn how to conduct user research, create wireframes, and design high-fidelity prototypes using Figma.",
    willLearn: ["User Research", "Wireframing", "Figma Basics", "Prototyping"]
  },
  {
    id: 4,
    img: "/machine.jpg",
    title: "Machine Learning A-Z",
    instructor: "Dr. Anietie",
    price: 150,
    level: "Advanced",
    category: "Data",
    duration: "30 Hours",
    description: "Build powerful Machine Learning models. This course covers everything from Linear Regression to Neural Networks and Deep Learning.",
    willLearn: ["Supervised Learning", "Random Forests", "Deep Learning", "Model Deployment"]
  },
  {
    id: 5,
    img: "/marketing.jpg",
    title: "Product Management Essentials",
    instructor: "prof. Dwight",
    price: 89,
    level: "Intermediate",
    category: "Business",
    duration: "20 Hours",
    description: "Learn how to manage the lifecycle of a product. Understand market research, product roadmaps, and how to work with engineering teams.",
    willLearn: ["Market Analysis", "Product Roadmaps", "Agile Methodology", "User Stories"]
  },
  {
    id: 6,
    img: "/Coding.jpg",
    title: "React.js — From Zero",
    instructor: "Prof. Deborah",
    price: 100,
    level: "Intermediate",
    category: "Web",
    duration: "25 Hours",
    description: "The most popular JavaScript library explained simply. Learn components, state management, and how to build fast, modern web applications.",
    willLearn: ["JSX Components", "State & Props", "React Router", "Context API"]
  },
  {
    id: 7,
    img: "/Leadership.jpg",
    title: "Time Management Mastery",
    instructor: "Dr. Becky",
    price: 35,
    level: "Beginner",
    category: "Self Improvement",
    duration: "5 Hours",
    description: "Stop procrastinating and start achieving. Learn proven techniques like the Pomodoro method and Eisenhower matrix to boost your productivity.",
    willLearn: ["Goal Setting", "Prioritization", "Focus Techniques", "Avoiding Burnout"]
  },
  {
    id: 8,
    img: "/sql.jpg",
    title: "Advanced SQL",
    instructor: "Prof. Darlington",
    price: 159,
    level: "Advanced",
    category: "Data",
    duration: "18 Hours",
    description: "Go beyond simple SELECT statements. Master complex joins, subqueries, and database optimization for large-scale data systems.",
    willLearn: ["Complex Joins", "Window Functions", "Indexing", "Query Optimization"]
  },
  {
    id: 9,
    img: "/marketing.jpg",
    title: "Financial Accounting",
    instructor: "Prof Emmanuella",
    price: 50,
    level: "Beginner",
    category: "Finance",
    duration: "22 Hours",
    description: "Understand the language of business. Learn how to read balance sheets, income statements, and manage corporate financial records.",
    willLearn: ["Bookkeeping", "Balance Sheets", "Cash Flow Statements", "Auditing Basics"]
  },
  {
    id: 10,
    img: "/marketing.jpg",
    title: "Digital Marketing Essentials",
    instructor: "Prof. Emmanuella",
    price: 100,
    level: "Intermediate",
    category: "Marketing",
    duration: "14 Hours",
    description: "Grow your business online. Master SEO, Social Media Marketing, and Email campaigns to reach a global audience.",
    willLearn: ["SEO Strategies", "Social Media Ads", "Content Marketing", "Email Automation"]
  },
  {
    id: 11,
    img: "/Rights.jpg",
    title: "Human Resource Management",
    instructor: "Prof Ime",
    price: 100,
    level: "Intermediate",
    category: "Business",
    duration: "20 Hours",
    description: "Learn how to build and lead great teams. This course covers recruitment, employee relations, and workplace culture development.",
    willLearn: ["Recruitment Strategy", "Conflict Resolution", "Employee Training", "Labor Laws"]
  },
  {
    id: 12,
    img: "/sql.jpg",
    title: "Database Management Systems",
    instructor: "Dr. Precious",
    price: 100,
    level: "Intermediate",
    category: "Data",
    duration: "24 Hours",
    description: "Learn the architecture of modern databases. Understand relational and non-relational systems and how to maintain data integrity.",
    willLearn: ["Relational Algebra", "Database Design", "Normalization", "Concurrency Control"]
  },
  {
    id: 13,
    img: "/mathsci.jpg",
    title: "Mathematics for Data Science",
    instructor: "Prof. Patrick",
    price: 100,
    level: "Intermediate",
    category: "Data",
    duration: "30 Hours",
    description: "The math behind the code. Master Linear Algebra, Calculus, and Probability theories essential for high-level data analysis.",
    willLearn: ["Linear Algebra", "Calculus", "Probability Theory", "Statistics"]
  },
  {
    id: 14,
    img: "/Coding.jpg",
    title: "Data Engineering",
    instructor: "Prof. David",
    price: 100,
    level: "Intermediate",
    category: "Data",
    duration: "28 Hours",
    description: "Build the pipelines that move data. Learn how to design ETL processes and manage big data infrastructures like Hadoop and Spark.",
    willLearn: ["ETL Pipelines", "Data Warehousing", "Big Data Tools", "Workflow Automation"]
  },
  {
    id: 15,
    img: "/Coding.jpg",
    title: "Mobile App Development",
    instructor: "Prof. Ihechi",
    price: 100,
    level: "Intermediate",
    category: "Software",
    duration: "35 Hours",
    description: "Build apps for iOS and Android. Using React Native, you will learn to create high-performance mobile applications from a single codebase.",
    willLearn: ["React Native", "Mobile UI Design", "API Integration", "App Store Deployment"]
  },
  {
    id: 16,
    img: "/Coding.jpg",
    title: "Cloud Computing with AWS",
    instructor: "prof. Miracle",
    price: 189,
    level: "Advanced",
    category: "Software",
    duration: "25 Hours",
    description: "Master the world's leading cloud platform. Learn to deploy, manage, and scale applications using Amazon Web Services (AWS).",
    willLearn: ["EC2 Instances", "S3 Storage", "Lambda Functions", "Cloud Security"]
  },
  {
    id: 17,
    img: "/Rights.jpg",
    title: "Ethics in the Workplace",
    instructor: "Prof. Faith",
    price: 100,
    level: "Intermediate",
    category: "Professional Studies",
    duration: "10 Hours",
    description: "Understand the importance of professional integrity. Learn how to navigate ethical dilemmas and foster a culture of respect and honesty.",
    willLearn: ["Ethical Decision Making", "Workplace Rights", "Code of Conduct", "Professionalism"]
  }
];

export default course;